version: '2'

services:

  conjur:
    image: registry.tld/conjur-appliance-cuke-master:4.9-stable
    privileged: true
    ports:
      - '443:443'  # Conjur API and web UI
    volumes:
      - .:/src
    working_dir: /src

  jenkins:
    build: .
    image: jenkins:2.60.1-conjur  # LTS release
    ports:
      - '8080:8080'  # Jenkins API and web UI
      - '50000:50000'  # Jenkins executor JNLP port
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - .:/src
